GET http://localhost:3000

### Get all the songs
GET http://localhost:3000/songs

### Get one song
GET http://localhost:3000/songs/4

### Update one song
PUT http://localhost:3000/songs/3

### Delete one song
DELETE  http://localhost:3000/songs/3

### Create a new song
POST http://localhost:3000/songs